#ifndef MAPNAME_H
#define MAPNAME_H

enum class MapName
{
    WORLD,
    TANTAGEL,
    TANTAGEL_THRONE_ROOM,
    TANTAGEL_CELLAR,
    BRECCONARY,
    BRECCONARY_TOOL_SHOP,
    BRECCONARY_HOLY_WELL,
    ERDRICKS_CAVE_1,
    ERDRICKS_CAVE_2,
    GARINHAM,
    GARINHAM_INTERIOR,
};

#endif